name: 'Domain and SSL cert watcher'
description: 'Watch SSL certs and registry date expiring for your domains'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'

inputs:
  url:
    description: 'url'
    required: true
  check_action:
    description: 'action'
    required: true
  # urls:
  #   description: 'Site domains to be checked (with protocol)'
  #   required: true
  # check_action:
  #   description: 'action'
  #   required: true
  # minimum_left_days:
  #   description: 'Minimum left days'
  #   type: number
  #   required: true
  # token:
  #   description: 'GitHub token'
  #   required: true
  # assignees:
  #   description: 'Issue Assignee'
  #   required: false

outputs:
  run-action:
    description: 'Run action'

  issue-body:
    description: 'Expiry records'

  urls:
    description: 'urls, debug info'

runs:
  using: 'node12'
  main: 'dist/index.js'
